import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Component/Header'
import Provider from './Provider'
import Navbar from './Component/Navbar'
import Search from './Component/Search'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header/>
          <Navbar/>
          <Search/>
          {children}
        </Provider>
        </body>
    </html>
  )
}
